import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ToastProvider from "../components/notifications/ToastProvider";
import NotificationBell from "../components/notifications/NotificationBell";
import NavLinks from "../components/NavLinks";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        <ToastProvider>
          <header className="sticky top-0 z-40 border-b border-border bg-background">
            <div className="flex items-center justify-between px-6 py-3">
              <div className="flex items-baseline gap-8">
                <a href="/" className="text-lg font-semibold text-foreground">
                  CareHub
                </a>
                <NavLinks />
              </div>
              <NotificationBell />
            </div>
          </header>
          {children}
        </ToastProvider>
      </body>
    </html>
  );
}
